---
title: "R Notebook"
output: html_notebook
---

```{r get smoking related snps}
# install.packages("ARTP2")
library(ARTP2)
library("readxl")
library("dplyr")



# Liu 2019 NG
# S Table 1 AgeSmk GWAS Sig
AgeSmk <- read_excel("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/liu_2019_ng/NIHMS1511852-supplement-2.xlsx", sheet = "S Table 1 AgeSmk GWAS Sig", skip = 1)
AgeSmk <- AgeSmk %>% filter(row_number() <= n()-3)
AgeSmk <- AgeSmk[1:12]
AgeSmk$Trait <- "AgeSmk"
colnames(AgeSmk) <- colnames(AgeSmk)

# S Table 2 CigDay GWAS Sig
CigDay <- read_excel("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/liu_2019_ng/NIHMS1511852-supplement-2.xlsx", sheet = "S Table 2 CigDay GWAS Sig", skip = 1)
CigDay <- CigDay %>% filter(row_number() <= n()-3)
CigDay <- CigDay[1:12]
CigDay$Trait <- "CigDay"
colnames(CigDay) <- colnames(AgeSmk)

# S Table 3 SmkCes GWAS Sig
SmkCes <- read_excel("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/liu_2019_ng/NIHMS1511852-supplement-2.xlsx", sheet = "S Table 3 SmkCes GWAS Sig", skip = 1)
SmkCes <- SmkCes %>% filter(row_number() <= n()-3)
SmkCes <- SmkCes[1:12]
SmkCes$Trait <- "SmkCes"
colnames(SmkCes) <- colnames(AgeSmk)

# S Table 4 SmkInit GWAS Sig
SmkInit <- read_excel("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/liu_2019_ng/NIHMS1511852-supplement-2.xlsx", sheet = "S Table 4 SmkInit GWAS Sig", skip = 1)
SmkInit <- SmkInit %>% filter(row_number() <= n()-3)
SmkInit <- SmkInit[1:12]
SmkInit$Trait <- "SmkInit"
colnames(SmkInit) <- colnames(AgeSmk)

# S Table 5 DrnkWk GWAS Sig
DrnkWk <- read_excel("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/liu_2019_ng/NIHMS1511852-supplement-2.xlsx", sheet = "S Table 5 DrnkWk GWAS Sig", skip = 1)
DrnkWk <- DrnkWk %>% filter(row_number() <= n()-3)
DrnkWk <- DrnkWk[1:12]
DrnkWk$Trait <- "DrnkWk"
colnames(DrnkWk) <- colnames(AgeSmk)

# combine smoking related SNPs 
smoking_snps <- rbind(AgeSmk,CigDay)
smoking_snps <- rbind(smoking_snps,SmkCes)
smoking_snps <- rbind(smoking_snps,SmkInit)
smoking_snps$"Pos plus 500K" <- smoking_snps$Pos+500000
smoking_snps$"Pos minus 500K" <- smoking_snps$Pos-500000
write.csv(smoking_snps,"/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/liu_2019_ng/Liu_2019_NG_smoking_snps.csv")
excluded.regions <-  smoking_snps %>% select("CHR" = "Chr","Start" = "Pos minus 500K","End" = "Pos plus 500K")

# getAnywhere(exclude.snps)
exclude.snps.rwp <- function (stat, excluded.regions) 
{
    if (!all(c("CHR", "position") %in% colnames(stat))) {
        msg <- "Columns 'CHR' and 'position' should be provided in stat"
        stop(msg)
    }
    if (!all(c("CHR", "Start", "End") %in% colnames(excluded.regions))) {
        msg <- "Columns 'CHR', 'Start' and 'End' should be provided in excluded.regions"
        stop(msg)
    }
    nregions <- nrow(excluded.regions)
    exc.rows <- NULL
    for (j in 1:nregions) {
        id <- which(stat$CHR == excluded.regions$CHR[j] & stat$position >= 
            excluded.regions$Start[j] & stat$position <= excluded.regions$End[j])
        exc.rows <- c(exc.rows, id)
    }
    if (!is.null(exc.rows)) {
        stat <- stat[-exc.rows, ]
    }
    stat
}

```


```{r process tricl oncoarray}
mckay_2017_colnames <- c("chr:pos","rs_number","CHR","position","reference_allele","effect_allele","EAF","OR_fixed","StdError_fixed","Pvalue_fixed","L95_fixed","U95_fixed","phete(Q)_Pvalue","I2","N_study","N_Cases","N_Controls","Effects","OR_random","StdError_random","Pvalue_random","L95_random","U95_random")

# overall
overall_mckay_2017 <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/tricl_onco_2017/overall.txt", skip = 1, header = F)
colnames(overall_mckay_2017) <- mckay_2017_colnames
overall_filtered <-  exclude.snps.rwp(overall_mckay_2017, excluded.regions)
dim(overall_filtered)[1] # 6756969
dim(overall_mckay_2017)[1] # 7673198
dim(overall_filtered)[1] / dim(overall_mckay_2017)[1] # 0.8805936
head(overall_filtered)
write.table(overall_filtered,"/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/tricl_onco_2017/overall_filtered.txt", row.names=FALSE, quote = FALSE, sep = ",")

# adeno
adeno_mckay_2017 <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/tricl_onco_2017/adeno.txt", skip = 1, header = F)
colnames(adeno_mckay_2017) <- mckay_2017_colnames
adeno_filtered <-  exclude.snps.rwp(adeno_mckay_2017, excluded.regions)
dim(adeno_filtered)[1] # 6756969
dim(adeno_mckay_2017)[1] # 7673198
dim(adeno_filtered)[1] / dim(adeno_mckay_2017)[1] # 0.8805936
write.table(adeno_filtered,"/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/tricl_onco_2017/adeno_filtered.txt", row.names=FALSE, quote = FALSE, sep = ",")

# squam
squam_mckay_2017 <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/tricl_onco_2017/squam.txt", skip = 1, header = F)
colnames(squam_mckay_2017) <- mckay_2017_colnames
squam_filtered <-  exclude.snps.rwp(squam_mckay_2017, excluded.regions)
dim(squam_filtered)[1] # 6756969
dim(squam_mckay_2017)[1] # 7673198
dim(squam_filtered)[1] / dim(squam_mckay_2017)[1] # 0.8805936
write.table(squam_filtered,"/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/tricl_onco_2017/squam_filtered.txt", row.names=FALSE, quote = FALSE, sep = ",")

# small
small_mckay_2017 <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/tricl_onco_2017/small.txt", skip = 1, header = F)
colnames(small_mckay_2017) <- mckay_2017_colnames
small_filtered <-  exclude.snps.rwp(small_mckay_2017, excluded.regions)
dim(small_filtered)[1] # 6756969
dim(small_mckay_2017)[1] # 7673198
dim(small_filtered)[1] / dim(small_mckay_2017)[1] # 0.8805936
write.table(small_filtered,"/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/tricl_onco_2017/small_filtered.txt", row.names=FALSE, quote = FALSE, sep = ",")

# never
never_mckay_2017 <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/tricl_onco_2017/never.txt", skip = 1, header = F)
colnames(never_mckay_2017) <- mckay_2017_colnames
never_filtered <-  exclude.snps.rwp(never_mckay_2017, excluded.regions)
dim(never_filtered)[1] # 6756969
dim(never_mckay_2017)[1] # 7673198
dim(never_filtered)[1] / dim(never_mckay_2017)[1] # 0.8805936
write.table(never_filtered,"/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/tricl_onco_2017/never_filtered.txt", row.names=FALSE, quote = FALSE, sep = ",")

# ever
ever_mckay_2017 <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/tricl_onco_2017/ever.txt", skip = 1, header = F)
colnames(ever_mckay_2017) <- mckay_2017_colnames
ever_filtered <-  exclude.snps.rwp(ever_mckay_2017, excluded.regions)
dim(ever_filtered)[1] # 6756969
dim(ever_mckay_2017)[1] # 7673198
dim(ever_filtered)[1] / dim(ever_mckay_2017)[1] # 0.8805936
write.table(ever_filtered,"/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/tricl_onco_2017/ever_filtered.txt", row.names=FALSE, quote = FALSE, sep = ",")

```


```{r UKBB trait accession}
library(readxl)
library(stringr)
# ukbb_trait_manifest <- read_excel("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/ukbb_traits/UKBB GWAS Imputed v3 - File Manifest Release 20180731.xlsx", sheet = "Manifest 201807")

ldsc_ready_ukbb_manifest <- read_excel("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/ukbb_traits/LDSC Sumstat Manifest for Neale UKB GWAS.xlsx", sheet ="ukb31063_ldsc_sumstat_manifest")
all_both_sexes <- ldsc_ready_ukbb_manifest[!grepl("male", ldsc_ready_ukbb_manifest$sex),]
all_both_sexes <- all_both_sexes[!grepl("_raw", all_both_sexes$`phenotype`),]
write.table(all_both_sexes$ldsc_sumstat_wget,"/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/ukbb_traits/all_both_sexes.txt",row.names=FALSE,sep="\t", quote = FALSE)

ldsr_ii_traits <- read_excel("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/ukbb_traits/UKBB GWAS Imputed v3 - File Manifest Release 20180731.xlsx", sheet = "To recover")

ldsr_ii_traits$lower <- tolower(ldsr_ii_traits$`Traits to recover`)
ldsr_ii_traits$lowerconcat <- tolower(ldsr_ii_traits$`Traits to recover`)
ldsr_ii_traits$lowerconcat <- gsub( ":", "", as.character(ldsr_ii_traits$lowerconcat))
ldsr_ii_traits$lowerconcat <- gsub( "@", "", as.character(ldsr_ii_traits$lowerconcat))
ldsr_ii_traits$lowerconcat <- gsub( "?", "", as.character(ldsr_ii_traits$lowerconcat))
ldsr_ii_traits$lowerconcat <- gsub( "/", "", as.character(ldsr_ii_traits$lowerconcat))
ldsr_ii_traits$lowerconcat <- gsub( ",", "", as.character(ldsr_ii_traits$lowerconcat))
ldsr_ii_traits$lowerconcat <- gsub( ">", "", as.character(ldsr_ii_traits$lowerconcat))
ldsr_ii_traits$lowerconcat <- gsub( "<", "", as.character(ldsr_ii_traits$lowerconcat))
ldsr_ii_traits$lowerconcat <- gsub( "-", "", as.character(ldsr_ii_traits$lowerconcat))
ldsr_ii_traits$lowerconcat <- gsub( "  ", "", as.character(ldsr_ii_traits$lowerconcat))
ldsr_ii_traits$lowerconcat <- gsub( " ", "", as.character(ldsr_ii_traits$lowerconcat))
ldsr_ii_traits$lowerconcat <- gsub( "#", "", as.character(ldsr_ii_traits$lowerconcat))
ldsr_ii_traits$lowerconcat <- gsub( "(", "", as.character(ldsr_ii_traits$lowerconcat), fixed =TRUE)
ldsr_ii_traits$lowerconcat <- gsub( ")", "", as.character(ldsr_ii_traits$lowerconcat), fixed =TRUE)
ldsr_ii_traits$lowerconcat <- gsub( ".", "", as.character(ldsr_ii_traits$lowerconcat), fixed =TRUE)
ldsr_ii_traits$lowerconcat <- gsub( "?", "", as.character(ldsr_ii_traits$lowerconcat), fixed =TRUE)
ldsr_ii_traits$lowerconcat <- gsub( "%", "", as.character(ldsr_ii_traits$lowerconcat), fixed =TRUE)
ldsr_ii_traits$lowerconcat <- gsub( "'", "", as.character(ldsr_ii_traits$lowerconcat), fixed =TRUE)
ldsr_ii_traits$lowerconcat <- gsub( "__", "", as.character(ldsr_ii_traits$lowerconcat))
ldsr_ii_traits$lowerconcat <- gsub( "_", "", as.character(ldsr_ii_traits$lowerconcat))
ldsr_ii_traits$lowerconcat <- gsub( "+", "", as.character(ldsr_ii_traits$lowerconcat))
ldsr_ii_traits$firstword <- word(ldsr_ii_traits$lower, 1)


ldsc_ready_ukbb_manifest$lower <- tolower(ldsc_ready_ukbb_manifest$`description`)
ldsc_ready_ukbb_manifest$lower_mod <- gsub( ":", "", as.character(ldsc_ready_ukbb_manifest$lower))
ldsc_ready_ukbb_manifest$lower_mod <- gsub( "@", "", as.character(ldsc_ready_ukbb_manifest$lower_mod))
ldsc_ready_ukbb_manifest$lower_mod <- gsub( "?", "", as.character(ldsc_ready_ukbb_manifest$lower_mod))
ldsc_ready_ukbb_manifest$lower_mod <- gsub( "/", "", as.character(ldsc_ready_ukbb_manifest$lower_mod))
ldsc_ready_ukbb_manifest$lower_mod <- gsub( ",", "", as.character(ldsc_ready_ukbb_manifest$lower_mod))
ldsc_ready_ukbb_manifest$lower_mod <- gsub( ">", "", as.character(ldsc_ready_ukbb_manifest$lower_mod))
ldsc_ready_ukbb_manifest$lower_mod <- gsub( "<", "", as.character(ldsc_ready_ukbb_manifest$lower_mod))
ldsc_ready_ukbb_manifest$lower_mod <- gsub( "-", "", as.character(ldsc_ready_ukbb_manifest$lower_mod))
ldsc_ready_ukbb_manifest$lower_mod <- gsub( "  ", "", as.character(ldsc_ready_ukbb_manifest$lower_mod))
ldsc_ready_ukbb_manifest$lower_mod <- gsub( " ", "", as.character(ldsc_ready_ukbb_manifest$lower_mod))
ldsc_ready_ukbb_manifest$lower_mod <- gsub( "#", "", as.character(ldsc_ready_ukbb_manifest$lower_mod))
ldsc_ready_ukbb_manifest$lower_mod <- gsub( "(", "", as.character(ldsc_ready_ukbb_manifest$lower_mod), fixed =TRUE)
ldsc_ready_ukbb_manifest$lower_mod <- gsub( ")", "", as.character(ldsc_ready_ukbb_manifest$lower_mod), fixed =TRUE)
ldsc_ready_ukbb_manifest$lower_mod <- gsub( ".", "", as.character(ldsc_ready_ukbb_manifest$lower_mod), fixed =TRUE)
ldsc_ready_ukbb_manifest$lower_mod <- gsub( "?", "", as.character(ldsc_ready_ukbb_manifest$lower_mod), fixed =TRUE)
ldsc_ready_ukbb_manifest$lower_mod <- gsub( "%", "", as.character(ldsc_ready_ukbb_manifest$lower_mod), fixed =TRUE)
ldsc_ready_ukbb_manifest$lower_mod <- gsub( "'", "", as.character(ldsc_ready_ukbb_manifest$lower_mod), fixed =TRUE)
ldsc_ready_ukbb_manifest$lower_mod <- gsub( "__", "", as.character(ldsc_ready_ukbb_manifest$lower_mod))
ldsc_ready_ukbb_manifest$lower_mod <- gsub( "_", "", as.character(ldsc_ready_ukbb_manifest$lower_mod))
ldsc_ready_ukbb_manifest$lower_mod <- gsub( "+", "", as.character(ldsc_ready_ukbb_manifest$lower_mod))

ldsc_ready_ukbb_manifest_filtered <- ldsc_ready_ukbb_manifest
ldsc_ready_ukbb_manifest_filtered <- ldsc_ready_ukbb_manifest_filtered[!grepl("male", ldsc_ready_ukbb_manifest_filtered$sex),]
ldsc_ready_ukbb_manifest_filtered <- ldsc_ready_ukbb_manifest_filtered[!grepl("_raw", ldsc_ready_ukbb_manifest_filtered$`phenotype`),]

# is it in our trait list?
sum(grepl(".", ldsc_ready_ukbb_manifest_filtered$lower_mod, fixed = TRUE))>0
keep_vector <- grepl(".", ldsc_ready_ukbb_manifest_filtered$lower_mod, fixed = TRUE)
for(i in ldsr_ii_traits$lowerconcat){ 
    if (sum(grepl(i, ldsc_ready_ukbb_manifest_filtered$lower_mod, fixed = TRUE))>0){
        keep_vector <- keep_vector + grepl(i, ldsc_ready_ukbb_manifest_filtered$lower_mod, fixed = TRUE)
    } else {
        print (i)
    }
}
# keep_vector

ldsc_ready_ukbb_manifest_filtered_final <- ldsc_ready_ukbb_manifest_filtered
ldsc_ready_ukbb_manifest_filtered_final$keep_vector <- keep_vector
ldsc_ready_ukbb_manifest_filtered_final <- ldsc_ready_ukbb_manifest_filtered_final[ldsc_ready_ukbb_manifest_filtered_final$keep_vector>0,]


# manually find (not caught on the keep vector search)
ldsc_ready_ukbb_manifest_toadd<- ldsc_ready_ukbb_manifest_filtered[0,]
# [1] "basalmetabolicrateimpedence"
tmp <- ldsc_ready_ukbb_manifest_filtered[grepl("basalmetabolic", ldsc_ready_ukbb_manifest_filtered$lower_mod),]
ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)
# [1] "birthweighttransethnic"
# tmp <- ldsc_ready_ukbb_manifest_filtered[grepl("trans", ldsc_ready_ukbb_manifest_filtered$lower_mod),]
# ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)

# [1] "bodybalding"
# tmp <- ldsc_ready_ukbb_manifest[grepl("bald", ldsc_ready_ukbb_manifest$lower_mod),]
# ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)


# [1] "bodybalding4"
# tmp <- ldsc_ready_ukbb_manifest[grepl("bald", ldsc_ready_ukbb_manifest$lower_mod),]
# ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)

# [1] "bodyheightz"
# tmp <- ldsc_ready_ukbb_manifest[grepl("height", ldsc_ready_ukbb_manifest$lower_mod),]
# ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)

# [1] "bpdiastolicadjmedz"
tmp <- ldsc_ready_ukbb_manifest_filtered[grepl("diastol", ldsc_ready_ukbb_manifest_filtered$lower_mod),]
ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)

# [1] "bpsystolicadjmedz"
tmp <- ldsc_ready_ukbb_manifest_filtered[grepl("systol", ldsc_ready_ukbb_manifest_filtered$lower_mod),]
ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)

# [1] "collegeeducation"
tmp <- ldsc_ready_ukbb_manifest_filtered[grepl("college", ldsc_ready_ukbb_manifest_filtered$lower_mod),]
ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)

# [1] "depressivesymptoms"
tmp <- ldsc_ready_ukbb_manifest_filtered[grepl("depress", ldsc_ready_ukbb_manifest_filtered$lower_mod),]
ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)

# [1] "extermewhrstage1"
tmp <- ldsc_ready_ukbb_manifest_filtered[grepl("waist", ldsc_ready_ukbb_manifest_filtered$lower_mod),]
ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)

# [1] "extremebmistage1"
tmp <- ldsc_ready_ukbb_manifest_filtered[grepl("bmi", ldsc_ready_ukbb_manifest_filtered$lower_mod),]
ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)

# [1] "heightalkes"

# [1] "mentalneuroticism"
tmp <- ldsc_ready_ukbb_manifest_filtered[grepl("neuroticism", ldsc_ready_ukbb_manifest_filtered$lower_mod),]
ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)

# [1] "noweartimebiasadjustedaccelerationstandarddeviation"

# [1] "numberofchildrenborntotal"
tmp <- ldsc_ready_ukbb_manifest_filtered[grepl("children", ldsc_ready_ukbb_manifest_filtered$lower_mod),]
ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)

# [1] "numberoflivebirths"

# [1] "obesityclass1"
tmp <- ldsc_ready_ukbb_manifest_filtered[grepl("obes", ldsc_ready_ukbb_manifest_filtered$lower_mod),]
ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)

# [1] "obesityclass2"
# [1] "obesityclass3"

# [1] "othermorningperson"

# [1] "overweightstage1"

# [1] "pigmenthair"

# [1] "pigmentsunburn"

# [1] "pigmenttanning"
tmp <- ldsc_ready_ukbb_manifest_filtered[grepl("tanning", ldsc_ready_ukbb_manifest_filtered$lower_mod),]
ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)

# [1] "repromenarcheage"
tmp <- ldsc_ready_ukbb_manifest_filtered[grepl("menarche", ldsc_ready_ukbb_manifest_filtered$lower_mod),]
ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)

# [1] "variabilityofbodymassindex"

# [1] "waisthipratiowhradjustedbmi"

# [1] "whr"

# [1] "whrwomen"

# [1] "yearsofeducation"
tmp <- ldsc_ready_ukbb_manifest_filtered[grepl("education", ldsc_ready_ukbb_manifest_filtered$lower_mod),]
ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)

# fitness
tmp <- ldsc_ready_ukbb_manifest_filtered[grepl("fitness", ldsc_ready_ukbb_manifest_filtered$lower_mod),]
ldsc_ready_ukbb_manifest_toadd <- rbind(ldsc_ready_ukbb_manifest_toadd,tmp)
ldsc_ready_ukbb_manifest_toadd$keep_vector <- 1



ldsc_ready_ukbb_manifest_filtered_final <- rbind(ldsc_ready_ukbb_manifest_filtered_final,ldsc_ready_ukbb_manifest_toadd)
ukbb_traits_wget <- subset(ldsc_ready_ukbb_manifest_filtered_final, select = -c(keep_vector))
ukbb_traits_wget <- unique(ukbb_traits_wget)

ukbb_traits_wget <- ukbb_traits_wget[!grepl("Food weight", ukbb_traits_wget$`description`),]
write.csv(ukbb_traits_wget,"/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/ukbb_traits/ukbb_traits_wget.csv")
# ukbb_traits_wget$URLS <- substring(ukbb_traits_wget$`wget command`, 6)

write.table(ukbb_traits_wget$ldsc_sumstat_wget,"/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/ukbb_traits/ukbb_traits_wget.txt",row.names=FALSE,sep="\t", quote = FALSE)







```

```{r}
library(tools)
library(stringr)
library(dplyr)

# rm(ldsc_ready_ukbb_manifest, ldsc_ready_ukbb_manifest_filtered, ldsc_ready_ukbb_manifest_filtered_final, ldsr_ii_traits, ldsc_ready_ukbb_manifest_toadd)
# rm(tmp, overall_raw_out, header_out, all_both_sexes)

# overall
overall_raw_out <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/short_ldsc_rg/overall.txt", sep = "", header =F)
header_out <- overall_raw_out[1,]
colnames(overall_raw_out) <- overall_raw_out[1,]
overall_raw_out <- overall_raw_out[-1,]
overall_raw_out$outcome <- overall_raw_out$p1
overall_raw_out <- overall_raw_out %>% mutate_at("outcome", str_replace, "tricl_onco_2017/tricl_munged/", "")
overall_raw_out <- overall_raw_out %>% mutate_at("outcome", str_replace, ".munged.txt.sumstats.gz", "")
overall_raw_out$ldsc_sumstat_file <- overall_raw_out$p2
overall_raw_out <- overall_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, "select_ukbb_traits/", "")
overall_raw_out <- overall_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, ".tsv.gz", ".tsv.bgz")
overall_merge <- merge(overall_raw_out,ukbb_traits_wget,by="ldsc_sumstat_file")
overall_merge$Phenotype <- toTitleCase(overall_merge$lower)

overall_filtered_raw_out <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/short_ldsc_rg/overall_filtered.txt", sep = "", header =F)
header_out <- overall_filtered_raw_out[1,]
colnames(overall_filtered_raw_out) <- overall_filtered_raw_out[1,]
overall_filtered_raw_out <- overall_filtered_raw_out[-1,]
overall_filtered_raw_out$outcome <- overall_filtered_raw_out$p1
overall_filtered_raw_out <- overall_filtered_raw_out %>% mutate_at("outcome", str_replace, "tricl_onco_2017/tricl_munged/", "")
overall_filtered_raw_out <- overall_filtered_raw_out %>% mutate_at("outcome", str_replace, ".munged.txt.sumstats.gz", "")
overall_filtered_raw_out$ldsc_sumstat_file <- overall_filtered_raw_out$p2
overall_filtered_raw_out <- overall_filtered_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, "select_ukbb_traits/", "")
overall_filtered_raw_out <- overall_filtered_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, ".tsv.gz", ".tsv.bgz")
overall_filtered_merge <- merge(overall_filtered_raw_out,ukbb_traits_wget,by="ldsc_sumstat_file")
overall_filtered_merge$Phenotype <- toTitleCase(overall_filtered_merge$lower)

# adeno
adeno_raw_out <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/short_ldsc_rg/adeno.txt", sep = "", header =F)
header_out <- adeno_raw_out[1,]
colnames(adeno_raw_out) <- adeno_raw_out[1,]
adeno_raw_out <- adeno_raw_out[-1,]
adeno_raw_out$outcome <- adeno_raw_out$p1
adeno_raw_out <- adeno_raw_out %>% mutate_at("outcome", str_replace, "tricl_onco_2017/tricl_munged/", "")
adeno_raw_out <- adeno_raw_out %>% mutate_at("outcome", str_replace, ".munged.txt.sumstats.gz", "")
adeno_raw_out$ldsc_sumstat_file <- adeno_raw_out$p2
adeno_raw_out <- adeno_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, "select_ukbb_traits/", "")
adeno_raw_out <- adeno_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, ".tsv.gz", ".tsv.bgz")
adeno_merge <- merge(adeno_raw_out,ukbb_traits_wget,by="ldsc_sumstat_file")
adeno_merge$Phenotype <- toTitleCase(adeno_merge$lower)

adeno_filtered_raw_out <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/short_ldsc_rg/adeno_filtered.txt", sep = "", header =F)
header_out <- adeno_filtered_raw_out[1,]
colnames(adeno_filtered_raw_out) <- adeno_filtered_raw_out[1,]
adeno_filtered_raw_out <- adeno_filtered_raw_out[-1,]
adeno_filtered_raw_out$outcome <- adeno_filtered_raw_out$p1
adeno_filtered_raw_out <- adeno_filtered_raw_out %>% mutate_at("outcome", str_replace, "tricl_onco_2017/tricl_munged/", "")
adeno_filtered_raw_out <- adeno_filtered_raw_out %>% mutate_at("outcome", str_replace, ".munged.txt.sumstats.gz", "")
adeno_filtered_raw_out$ldsc_sumstat_file <- adeno_filtered_raw_out$p2
adeno_filtered_raw_out <- adeno_filtered_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, "select_ukbb_traits/", "")
adeno_filtered_raw_out <- adeno_filtered_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, ".tsv.gz", ".tsv.bgz")
adeno_filtered_merge <- merge(adeno_filtered_raw_out,ukbb_traits_wget,by="ldsc_sumstat_file")
adeno_filtered_merge$Phenotype <- toTitleCase(adeno_filtered_merge$lower)


# small
small_raw_out <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/short_ldsc_rg/small.txt", sep = "", header =F)
header_out <- small_raw_out[1,]
colnames(small_raw_out) <- small_raw_out[1,]
small_raw_out <- small_raw_out[-1,]
small_raw_out$outcome <- small_raw_out$p1
small_raw_out <- small_raw_out %>% mutate_at("outcome", str_replace, "tricl_onco_2017/tricl_munged/", "")
small_raw_out <- small_raw_out %>% mutate_at("outcome", str_replace, ".munged.txt.sumstats.gz", "")
small_raw_out$ldsc_sumstat_file <- small_raw_out$p2
small_raw_out <- small_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, "select_ukbb_traits/", "")
small_raw_out <- small_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, ".tsv.gz", ".tsv.bgz")
small_merge <- merge(small_raw_out,ukbb_traits_wget,by="ldsc_sumstat_file")
small_merge$Phenotype <- toTitleCase(small_merge$lower)

small_filtered_raw_out <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/short_ldsc_rg/small_filtered.txt", sep = "", header =F)
header_out <- small_filtered_raw_out[1,]
colnames(small_filtered_raw_out) <- small_filtered_raw_out[1,]
small_filtered_raw_out <- small_filtered_raw_out[-1,]
small_filtered_raw_out$outcome <- small_filtered_raw_out$p1
small_filtered_raw_out <- small_filtered_raw_out %>% mutate_at("outcome", str_replace, "tricl_onco_2017/tricl_munged/", "")
small_filtered_raw_out <- small_filtered_raw_out %>% mutate_at("outcome", str_replace, ".munged.txt.sumstats.gz", "")
small_filtered_raw_out$ldsc_sumstat_file <- small_filtered_raw_out$p2
small_filtered_raw_out <- small_filtered_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, "select_ukbb_traits/", "")
small_filtered_raw_out <- small_filtered_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, ".tsv.gz", ".tsv.bgz")
small_filtered_merge <- merge(small_filtered_raw_out,ukbb_traits_wget,by="ldsc_sumstat_file")
small_filtered_merge$Phenotype <- toTitleCase(small_filtered_merge$lower)


# squam
squam_raw_out <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/short_ldsc_rg/squam.txt", sep = "", header =F)
header_out <- squam_raw_out[1,]
colnames(squam_raw_out) <- squam_raw_out[1,]
squam_raw_out <- squam_raw_out[-1,]
squam_raw_out$outcome <- squam_raw_out$p1
squam_raw_out <- squam_raw_out %>% mutate_at("outcome", str_replace, "tricl_onco_2017/tricl_munged/", "")
squam_raw_out <- squam_raw_out %>% mutate_at("outcome", str_replace, ".munged.txt.sumstats.gz", "")
squam_raw_out$ldsc_sumstat_file <- squam_raw_out$p2
squam_raw_out <- squam_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, "select_ukbb_traits/", "")
squam_raw_out <- squam_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, ".tsv.gz", ".tsv.bgz")
squam_merge <- merge(squam_raw_out,ukbb_traits_wget,by="ldsc_sumstat_file")
squam_merge$Phenotype <- toTitleCase(squam_merge$lower)

squam_filtered_raw_out <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/short_ldsc_rg/squam_filtered.txt", sep = "", header =F)
header_out <- squam_filtered_raw_out[1,]
colnames(squam_filtered_raw_out) <- squam_filtered_raw_out[1,]
squam_filtered_raw_out <- squam_filtered_raw_out[-1,]
squam_filtered_raw_out$outcome <- squam_filtered_raw_out$p1
squam_filtered_raw_out <- squam_filtered_raw_out %>% mutate_at("outcome", str_replace, "tricl_onco_2017/tricl_munged/", "")
squam_filtered_raw_out <- squam_filtered_raw_out %>% mutate_at("outcome", str_replace, ".munged.txt.sumstats.gz", "")
squam_filtered_raw_out$ldsc_sumstat_file <- squam_filtered_raw_out$p2
squam_filtered_raw_out <- squam_filtered_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, "select_ukbb_traits/", "")
squam_filtered_raw_out <- squam_filtered_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, ".tsv.gz", ".tsv.bgz")
squam_filtered_merge <- merge(squam_filtered_raw_out,ukbb_traits_wget,by="ldsc_sumstat_file")
squam_filtered_merge$Phenotype <- toTitleCase(squam_filtered_merge$lower)

# never
never_raw_out <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/short_ldsc_rg/never.txt", sep = "", header =F)
header_out <- never_raw_out[1,]
colnames(never_raw_out) <- never_raw_out[1,]
never_raw_out <- never_raw_out[-1,]
never_raw_out$outcome <- never_raw_out$p1
never_raw_out <- never_raw_out %>% mutate_at("outcome", str_replace, "tricl_onco_2017/tricl_munged/", "")
never_raw_out <- never_raw_out %>% mutate_at("outcome", str_replace, ".munged.txt.sumstats.gz", "")
never_raw_out$ldsc_sumstat_file <- never_raw_out$p2
never_raw_out <- never_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, "select_ukbb_traits/", "")
never_raw_out <- never_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, ".tsv.gz", ".tsv.bgz")
never_merge <- merge(never_raw_out,ukbb_traits_wget,by="ldsc_sumstat_file")
never_merge$Phenotype <- toTitleCase(never_merge$lower)

never_filtered_raw_out <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/short_ldsc_rg/never_filtered.txt", sep = "", header =F)
header_out <- never_filtered_raw_out[1,]
colnames(never_filtered_raw_out) <- never_filtered_raw_out[1,]
never_filtered_raw_out <- never_filtered_raw_out[-1,]
never_filtered_raw_out$outcome <- never_filtered_raw_out$p1
never_filtered_raw_out <- never_filtered_raw_out %>% mutate_at("outcome", str_replace, "tricl_onco_2017/tricl_munged/", "")
never_filtered_raw_out <- never_filtered_raw_out %>% mutate_at("outcome", str_replace, ".munged.txt.sumstats.gz", "")
never_filtered_raw_out$ldsc_sumstat_file <- never_filtered_raw_out$p2
never_filtered_raw_out <- never_filtered_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, "select_ukbb_traits/", "")
never_filtered_raw_out <- never_filtered_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, ".tsv.gz", ".tsv.bgz")
never_filtered_merge <- merge(never_filtered_raw_out,ukbb_traits_wget,by="ldsc_sumstat_file")
never_filtered_merge$Phenotype <- toTitleCase(never_filtered_merge$lower)


# ever
ever_raw_out <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/short_ldsc_rg/ever.txt", sep = "", header =F)
header_out <- ever_raw_out[1,]
colnames(ever_raw_out) <- ever_raw_out[1,]
ever_raw_out <- ever_raw_out[-1,]
ever_raw_out$outcome <- ever_raw_out$p1
ever_raw_out <- ever_raw_out %>% mutate_at("outcome", str_replace, "tricl_onco_2017/tricl_munged/", "")
ever_raw_out <- ever_raw_out %>% mutate_at("outcome", str_replace, ".munged.txt.sumstats.gz", "")
ever_raw_out$ldsc_sumstat_file <- ever_raw_out$p2
ever_raw_out <- ever_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, "select_ukbb_traits/", "")
ever_raw_out <- ever_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, ".tsv.gz", ".tsv.bgz")
ever_merge <- merge(ever_raw_out,ukbb_traits_wget,by="ldsc_sumstat_file")
ever_merge$Phenotype <- toTitleCase(ever_merge$lower)

ever_filtered_raw_out <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/short_ldsc_rg/ever_filtered.txt", sep = "", header =F)
header_out <- ever_filtered_raw_out[1,]
colnames(ever_filtered_raw_out) <- ever_filtered_raw_out[1,]
ever_filtered_raw_out <- ever_filtered_raw_out[-1,]
ever_filtered_raw_out$outcome <- ever_filtered_raw_out$p1
ever_filtered_raw_out <- ever_filtered_raw_out %>% mutate_at("outcome", str_replace, "tricl_onco_2017/tricl_munged/", "")
ever_filtered_raw_out <- ever_filtered_raw_out %>% mutate_at("outcome", str_replace, ".munged.txt.sumstats.gz", "")
ever_filtered_raw_out$ldsc_sumstat_file <- ever_filtered_raw_out$p2
ever_filtered_raw_out <- ever_filtered_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, "select_ukbb_traits/", "")
ever_filtered_raw_out <- ever_filtered_raw_out %>% mutate_at("ldsc_sumstat_file", str_replace, ".tsv.gz", ".tsv.bgz")
ever_filtered_merge <- merge(ever_filtered_raw_out,ukbb_traits_wget,by="ldsc_sumstat_file")
ever_filtered_merge$Phenotype <- toTitleCase(ever_filtered_merge$lower)

overall_master <- rbind(overall_merge,overall_filtered_merge)
adeno_master <- rbind(adeno_merge,adeno_filtered_merge)
small_master <- rbind(small_merge,small_filtered_merge)
squam_master <- rbind(squam_merge,squam_filtered_merge)
never_master <- rbind(never_merge,never_filtered_merge)
ever_master <- rbind(ever_merge,ever_filtered_merge)

merge_master <- rbind(overall_master,adeno_master)
merge_master <- rbind(merge_master,small_master)
merge_master <- rbind(merge_master,squam_master)
merge_master <- rbind(merge_master,never_master)
merge_master <- rbind(merge_master,ever_master)

# sort(unique(merge_master$outcome))
write.csv(merge_master,"/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/short_ldsc_rg/merge_master.csv")



```


```{r}
# library("ggsci")
library("ggplot2")
library("scales")
library("gridExtra")
library("grid")
library(dplyr)

rm(list=setdiff(ls(), "merge_master"))

merge_master <- read.csv("/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/lung/ldsr_lung_ii/manuscript/naturesr_revision/references/short_ldsc_rg/merge_master.csv")

final_columns <- unique(merge_master) %>% select("outcome","Phenotype", everything(), -c("ldsc_sumstat_file","p1","p2","ldsc_sumstat_dropbox","ldsc_sumstat_wget","gwas_file","gwas_dropbox","gwas_wget","sex","is_v2","has_v2_replacement","dilute","is_primary_gwas","lower","lower_mod","phenotype","description")) 
final_columns$neglog10 <- -log10(as.numeric(final_columns$p))
final_columns$rg <- as.numeric(final_columns$rg)
final_columns$se <- as.numeric(final_columns$se)
final_columns$z <- as.numeric(final_columns$z)
final_columns$p <- as.numeric(final_columns$p)
final_columns <- final_columns %>% mutate(display_p = case_when(p<0.0000001~"***", p<0.000001~"**", p<0.00001~"*"))
final_columns$h2_obs <- as.numeric(final_columns$h2_obs)
final_columns <- final_columns %>% mutate(display_outcome = case_when( 
    outcome == "overall" ~ "Lung Cancer", 
    outcome == "overall_filtered" ~ "Lung Cancer †", 
    outcome == "adeno" ~ "Adenocarcinoma (LUAD)", 
    outcome == "adeno_filtered" ~ "Adenocarcinoma (LUAD) †", 
    outcome == "small" ~ "Small Cell Carcinoma (SCLC)", 
    outcome == "small_filtered" ~ "Small Cell Carcinoma (SCLC) †", 
    outcome == "squam" ~ "Squamous Cell Carcinoma (LUSC)", 
    outcome == "squam_filtered" ~ "Squamous Cell Carcinoma (LUSC) †", 
    outcome == "ever" ~ "Ever Smokers (>100 lifetime cigarettes)", 
    outcome == "ever_filtered" ~ "Ever Smokers (>100 lifetime cigarettes) †", 
    outcome == "never" ~ "Never Smokers (<100 lifetime cigarettes)", 
    outcome == "never_filtered" ~ "Never Smokers (<100 lifetime cigarettes) †"))
final_columns$display_outcome <- factor(final_columns$display_outcome, levels = c("Lung Cancer", "Lung Cancer †", "Adenocarcinoma (LUAD)",  "Adenocarcinoma (LUAD) †", "Small Cell Carcinoma (SCLC)", "Small Cell Carcinoma (SCLC) †", "Squamous Cell Carcinoma (LUSC)",  "Squamous Cell Carcinoma (LUSC) †", "Ever Smokers (>100 lifetime cigarettes)", "Ever Smokers (>100 lifetime cigarettes) †", "Never Smokers (<100 lifetime cigarettes)", "Never Smokers (<100 lifetime cigarettes) †"))


final_columns$combined <- paste(final_columns$outcome, final_columns$Phenotype)
final_columns <- distinct(final_columns,combined, .keep_all= TRUE)
# final_columns <- final_columns %>% filter(h2_obs > 0)
# write.csv(final_columns,"/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/analysis/revision_select_ukbb_traits.csv")

supp_5 <- final_columns %>% select(-c(neglog10,display_p,outcome,combined)) %>% select(display_outcome, everything()) %>% rename(Outcome = display_outcome, Trait = Phenotype, URL = showcase, "h2" = h2_obs,"h2 se" = h2_obs_se, "h2 int" = "h2_int","h2 int se" = "h2_int_se", "gcov int" = "gcov_int","gcov int se" = "gcov_int_se" ,"variable type" = "variable_type" ,"ldsc confidence" = "ldsc_confidence", "ldsc h2 significance"  ="ldsc_h2_significance" ) %>% select(-URL, URL) %>% select(Trait, everything()) %>% group_by(Trait, Outcome)

#  overall 381 traits
overall_final <-  supp_5 %>% filter(Outcome == "Lung Cancer")
overall_rem_final <- supp_5 %>% filter(Outcome == "Lung Cancer †")
# overall_final$Trait == overall_rem_final$Trait
overall_wide <- left_join(overall_final,overall_rem_final,by ="Trait") %>% select(-c("source.x","variable type.x","ldsc confidence.x","ldsc h2 significance.x" ,"URL.x","Outcome.y")) %>% 
    rename("Outcome" = "Outcome.x", "rg" = "rg.x" ,"se" = "se.x" , "z"= "z.x", "p" = "p.x" ,"h2" =  "h2.x" ,"h2 se"= "h2 se.x", "h2 int" = "h2 int.x" ,
           "h2 int se" ="h2 int se.x","gcov int"= "gcov int.x","gcov int se" = "gcov int se.x", "rg †" ="rg.y", "se †" = "se.y" , "z †" ="z.y",
           "p †" = "p.y", "h2 †" = "h2.y", "h2 se †" = "h2 se.y" ,"h2 int †" = "h2 int.y" ,"h2 int se †" = "h2 int se.y","gcov int †" ="gcov int.y",
           "gcov int se †" = "gcov int se.y","source" = "source.y", "variable type" = "variable type.y", "ldsc confidence" = "ldsc confidence.y", "ldsc h2 significance" ="ldsc h2 significance.y", "url" = "URL.y")

#  adeno 381 traits
adeno_final <-  supp_5 %>% filter(Outcome == "Adenocarcinoma (LUAD)")
adeno_rem_final <- supp_5 %>% filter(Outcome == "Adenocarcinoma (LUAD) †")
# adeno_final$Trait == adeno_rem_final$Trait
adeno_wide <- left_join(adeno_final,adeno_rem_final,by ="Trait") %>% select(-c("source.x","variable type.x","ldsc confidence.x","ldsc h2 significance.x" ,"URL.x","Outcome.y")) %>% 
    rename("Outcome" = "Outcome.x", "rg" = "rg.x" ,"se" = "se.x" , "z"= "z.x", "p" = "p.x" ,"h2" =  "h2.x" ,"h2 se"= "h2 se.x", "h2 int" = "h2 int.x" ,
           "h2 int se" ="h2 int se.x","gcov int"= "gcov int.x","gcov int se" = "gcov int se.x", "rg †" ="rg.y", "se †" = "se.y" , "z †" ="z.y",
           "p †" = "p.y", "h2 †" = "h2.y", "h2 se †" = "h2 se.y" ,"h2 int †" = "h2 int.y" ,"h2 int se †" = "h2 int se.y","gcov int †" ="gcov int.y",
           "gcov int se †" = "gcov int se.y","source" = "source.y", "variable type" = "variable type.y", "ldsc confidence" = "ldsc confidence.y", "ldsc h2 significance" ="ldsc h2 significance.y", "url" = "URL.y")

#  small 381 traits
small_final <-  supp_5 %>% filter(Outcome == "Small Cell Carcinoma (SCLC)")
small_rem_final <- supp_5 %>% filter(Outcome == "Small Cell Carcinoma (SCLC) †")
# small_final$Trait == small_rem_final$Trait
small_wide <- left_join(small_final,small_rem_final,by ="Trait") %>% select(-c("source.x","variable type.x","ldsc confidence.x","ldsc h2 significance.x" ,"URL.x","Outcome.y")) %>% 
    rename("Outcome" = "Outcome.x", "rg" = "rg.x" ,"se" = "se.x" , "z"= "z.x", "p" = "p.x" ,"h2" =  "h2.x" ,"h2 se"= "h2 se.x", "h2 int" = "h2 int.x" ,
           "h2 int se" ="h2 int se.x","gcov int"= "gcov int.x","gcov int se" = "gcov int se.x", "rg †" ="rg.y", "se †" = "se.y" , "z †" ="z.y",
           "p †" = "p.y", "h2 †" = "h2.y", "h2 se †" = "h2 se.y" ,"h2 int †" = "h2 int.y" ,"h2 int se †" = "h2 int se.y","gcov int †" ="gcov int.y",
           "gcov int se †" = "gcov int se.y","source" = "source.y", "variable type" = "variable type.y", "ldsc confidence" = "ldsc confidence.y", "ldsc h2 significance" ="ldsc h2 significance.y", "url" = "URL.y")

#  squam 381 traits
squam_final <-  supp_5 %>% filter(Outcome == "Squamous Cell Carcinoma (LUSC)")
squam_rem_final <- supp_5 %>% filter(Outcome == "Squamous Cell Carcinoma (LUSC) †")
# squam_final$Trait == squam_rem_final$Trait
squam_wide <- left_join(squam_final,squam_rem_final,by ="Trait") %>% select(-c("source.x","variable type.x","ldsc confidence.x","ldsc h2 significance.x" ,"URL.x","Outcome.y")) %>% 
    rename("Outcome" = "Outcome.x", "rg" = "rg.x" ,"se" = "se.x" , "z"= "z.x", "p" = "p.x" ,"h2" =  "h2.x" ,"h2 se"= "h2 se.x", "h2 int" = "h2 int.x" ,
           "h2 int se" ="h2 int se.x","gcov int"= "gcov int.x","gcov int se" = "gcov int se.x", "rg †" ="rg.y", "se †" = "se.y" , "z †" ="z.y",
           "p †" = "p.y", "h2 †" = "h2.y", "h2 se †" = "h2 se.y" ,"h2 int †" = "h2 int.y" ,"h2 int se †" = "h2 int se.y","gcov int †" ="gcov int.y",
           "gcov int se †" = "gcov int se.y","source" = "source.y", "variable type" = "variable type.y", "ldsc confidence" = "ldsc confidence.y", "ldsc h2 significance" ="ldsc h2 significance.y", "url" = "URL.y")

#  ever 381 traits
ever_final <-  supp_5 %>% filter(Outcome == "Ever Smokers (>100 lifetime cigarettes)")
ever_rem_final <- supp_5 %>% filter(Outcome == "Ever Smokers (>100 lifetime cigarettes) †")
# ever_final$Trait == ever_rem_final$Trait
ever_wide <- left_join(ever_final,ever_rem_final,by ="Trait") %>% select(-c("source.x","variable type.x","ldsc confidence.x","ldsc h2 significance.x" ,"URL.x","Outcome.y")) %>% 
    rename("Outcome" = "Outcome.x", "rg" = "rg.x" ,"se" = "se.x" , "z"= "z.x", "p" = "p.x" ,"h2" =  "h2.x" ,"h2 se"= "h2 se.x", "h2 int" = "h2 int.x" ,
           "h2 int se" ="h2 int se.x","gcov int"= "gcov int.x","gcov int se" = "gcov int se.x", "rg †" ="rg.y", "se †" = "se.y" , "z †" ="z.y",
           "p †" = "p.y", "h2 †" = "h2.y", "h2 se †" = "h2 se.y" ,"h2 int †" = "h2 int.y" ,"h2 int se †" = "h2 int se.y","gcov int †" ="gcov int.y",
           "gcov int se †" = "gcov int se.y","source" = "source.y", "variable type" = "variable type.y", "ldsc confidence" = "ldsc confidence.y", "ldsc h2 significance" ="ldsc h2 significance.y", "url" = "URL.y")

#  never 381 traits
never_final <-  supp_5 %>% filter(Outcome == "Never Smokers (<100 lifetime cigarettes)")
never_rem_final <- supp_5 %>% filter(Outcome == "Never Smokers (<100 lifetime cigarettes) †")
# never_final$Trait == never_rem_final$Trait
never_wide <- left_join(never_final,never_rem_final,by ="Trait") %>% select(-c("source.x","variable type.x","ldsc confidence.x","ldsc h2 significance.x" ,"URL.x","Outcome.y")) %>% 
    rename("Outcome" = "Outcome.x", "rg" = "rg.x" ,"se" = "se.x" , "z"= "z.x", "p" = "p.x" ,"h2" =  "h2.x" ,"h2 se"= "h2 se.x", "h2 int" = "h2 int.x" ,
           "h2 int se" ="h2 int se.x","gcov int"= "gcov int.x","gcov int se" = "gcov int se.x", "rg †" ="rg.y", "se †" = "se.y" , "z †" ="z.y",
           "p †" = "p.y", "h2 †" = "h2.y", "h2 se †" = "h2 se.y" ,"h2 int †" = "h2 int.y" ,"h2 int se †" = "h2 int se.y","gcov int †" ="gcov int.y",
           "gcov int se †" = "gcov int se.y","source" = "source.y", "variable type" = "variable type.y", "ldsc confidence" = "ldsc confidence.y", "ldsc h2 significance" ="ldsc h2 significance.y", "url" = "URL.y")

supp5wide <- rbind(overall_wide,adeno_wide)
supp5wide <- rbind(supp5wide,small_wide)
supp5wide <- rbind(supp5wide,squam_wide)
supp5wide <- rbind(supp5wide,ever_wide)
supp5wide <- rbind(supp5wide,never_wide)
supp5wide <-  supp5wide %>% select(Outcome, everything())

# write.csv(supp5wide,"/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/analysis/supp_5.csv")



sort(unique(supp5wide$Trait))


# install.packages("kableExtra")
library(kableExtra)
library(forcats)
# output_supp_5 <- supp_5 %>% kbl() %>% kable_classic(full_width = F, html_font = "Arial") %>% pack_rows(index = table(fct_inorder(supp_5$Trait)))
# output_supp_5




final_columns2 <- final_columns %>% filter(h2_obs > 0)
bonfsig <- final_columns2 %>% filter(p<.00001183712)  # 352
# 0.05 / (352 *12) = 1.183712e-05 = .00001183712
# -log10(1.183712e-05) # 4.926754

352 *6*2
1734/6
1734*2

vecbonfsigs <- sort(unique(bonfsig$Phenotype))
dropvec <- c("Illnesses of Father: None of the above (Group 2)","Leisure/Social Activities: Adult Education Class","Leisure/Social Activities: None of the above", "Medication for Pain Relief, Constipation, Heartburn: None of the above", "Medication for Pain Relief, Constipation, Heartburn: Paracetamol", "Mouth/Teeth Dental Problems: None of the above", "Noisy Workplace", "Number of Full Brothers" , "Pain Type(s) Experienced in Last Month: None of the above" , "Reason for Glasses/Contact Lenses: For Short-Sightedness, i.e. Only or Mainly for Distance Viewing Such as Driving, Cinema Etc (Called 'myopia')", "Shortness of Breath Walking on Level Ground", "Wheeze or Whistling in the Chest in Last Year", "Duration of Vigorous Activity")      

`%notin%` <- Negate(`%in%`)
sigtraits <- unique(final_columns2) %>% filter(Phenotype %in% vecbonfsigs & Phenotype %notin% dropvec ) %>% filter(display_outcome %notin% c("Ever Smokers (>100 lifetime cigarettes)", "Ever Smokers (>100 lifetime cigarettes) †", "Never Smokers (<100 lifetime cigarettes)", "Never Smokers (<100 lifetime cigarettes) †"))
sigoverall <-  sigtraits %>% filter(display_outcome == "Lung Cancer")
sigoverall <- sigoverall[order(sigoverall$rg),]
traitordervec <- unique(sigoverall$Phenotype)
sigtraits$Phenotype <- factor(sigtraits$Phenotype, levels = traitordervec)
sigtraits$combined <- paste(sigtraits$outcome, sigtraits$Phenotype)
sigtraits_final <- distinct(sigtraits,combined, .keep_all= TRUE)




sigtraits

# fig_2 <- fig_2 + scale_color_npg() + scale_fill_npg() # change coloring
# fig_2 <- fig_2 + scale_color_lancet() + scale_fill_lancet() # change coloring

ggplot(sigtraits_final, aes(x = display_outcome, y = Phenotype, fill = rg)) + 
    geom_tile() + 
    geom_text(data=sigtraits_final, aes(display_outcome, Phenotype, label=paste(paste(format(round(rg, digits = 2),nsmall=2)),ifelse(is.na(display_p), "", display_p), sep=" ")),size = 4, color="black") +
    scale_x_discrete(position = "top", expand = c(0, 0)) + 
    scale_fill_gradient2(low="blue",high="red", mid="white",midpoint = 0,limits=c(-.82,.82)) +
    theme(text = element_text(size = 16, color="black"),
          plot.margin = margin(.5,.5,.5,.5,"cm"), 
          axis.title.x = element_text(color="black", size=20, face="bold", hjust = 0.5),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0, color="black", size=15),
          axis.title.y = element_text(color="black", size=20, face="bold"),
          axis.text.y = element_text(color="black", size=15,),
          legend.title = element_text(color="black", size=16, hjust = 0.5),
          legend.text=element_text(color="black", size=16, hjust = 0.5),
          panel.border = element_rect(fill=NA,color="gray90", size=0.5, linetype="solid")) +
    labs(x = "Lung Cancer Outcomes", y = "Significant Traits", fill = "† indicates\nremoval of smoking\nrelated SNPs\n\n\n\nSignificance\n* p<0.00001\n** p<0.000001\n*** p<0.0000001\n\n\n\nGenetic\nCorrelation\n(rg)")+ 

# ggsave("Figure 6.png", path ="/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/manuscript/tables and figures/", dpi = 1200, height = 20 , width = 20, device = "png", limitsize = FALSE)



```



```{r}

`%notin%` <- Negate(`%in%`)
sigfit <- unique(final_columns2) %>% filter(Phenotype %in% fitness_traits) %>% filter(display_outcome %notin% c("Ever Smokers (>100 lifetime cigarettes)", "Ever Smokers (>100 lifetime cigarettes) †", "Never Smokers (<100 lifetime cigarettes)", "Never Smokers (<100 lifetime cigarettes) †"))
sigoverall <-  sigfit %>% filter(display_outcome == "Lung Cancer")
sigoverall <- sigoverall[order(sigoverall$rg),]
traitordervec <- unique(sigoverall$Phenotype)
sigfit$Phenotype <- factor(sigfit$Phenotype, levels = traitordervec)
sigfit$combined <- paste(sigfit$outcome, sigfit$Phenotype)
sigfit_final <- distinct(sigfit,combined, .keep_all= TRUE)


ggplot(sigfit_final, aes(x = display_outcome, y = Phenotype, fill = rg)) + 
    geom_tile() + 
    geom_text(data=sigfit_final, aes(display_outcome, Phenotype, label=paste(paste(format(round(rg, digits = 2),nsmall=2)),ifelse(is.na(display_p), "", display_p), sep=" ")),size = 4, color="black") +
    scale_x_discrete(position = "top", expand = c(0, 0)) + 
    scale_fill_gradient2(low="blue",high="red", mid="white",midpoint = 0,limits=c(-.82,.82)) +
    theme(text = element_text(size = 16, color="black"),
          plot.margin = margin(.5,.5,.5,.5,"cm"), 
          axis.title.x = element_text(color="black", size=20, face="bold", hjust = 0.5),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0, color="black", size=15),
          axis.title.y = element_text(color="black", size=20, face="bold"),
          axis.text.y = element_text(color="black", size=15,),
          legend.title = element_text(color="black", size=16, hjust = 0.5),
          legend.text=element_text(color="black", size=16, hjust = 0.5),
          panel.border = element_rect(fill=NA,color="gray90", size=0.5, linetype="solid")) +
    labs(x = "Lung Cancer Outcomes", y = "Fitness Traits", fill = "† indicates\nremoval of smoking\nrelated SNPs\n\n\n\nSignificance\n* p<0.00001\n** p<0.000001\n*** p<0.0000001\n\n\n\nGenetic\nCorrelation\n(rg)")

# ggsave("Supplementary Figure 2.png", path ="/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/manuscript/tables and figures/", dpi = 1200, height = 20 , width = 20, device = "png", limitsize = FALSE)

```



```{r}
fitness_traits <- c("Arm Fat Mass (Left)","Arm Fat Mass (Right)","Arm Fat Percentage (Left)","Arm Fat Percentage (Right)","Arm Fat-Free Mass (Left)", "Arm Fat-Free Mass (Right)", "Arm Predicted Mass (Left)", "Arm Predicted Mass (Right)", "Basal Metabolic Rate", "Body Fat Percentage", "Body Mass Index (Bmi)", "Duration of Fitness Test", "Duration of Heavy Diy", "Duration of Light Diy", "Duration of Moderate Activity" ,"Duration of Other Exercises", "Duration of Strenuous Sports", "Duration of Vigorous Activity", "Duration of Walks", "Duration of Worst Depression" ,"Duration Walking for Pleasure" ,"Falls in the Last Year", "Frequency of Heavy Diy in Last 4 Weeks", "Frequency of Light Diy in Last 4 Weeks" ,"Frequency of Other Exercises in Last 4 Weeks" ,"Frequency of Stair Climbing in Last 4 Weeks", "Frequency of Tenseness / Restlessness in Last 2 Weeks", "Frequency of Tiredness / Lethargy in Last 2 Weeks", "Frequency of Walking for Pleasure in Last 4 Weeks", "Hand Grip Strength (Left)", "Hand Grip Strength (Right)" ,"Hip Circumference","Impedance of Arm (Left)","Impedance of Arm (Right)", "Impedance of Leg (Left)","Impedance of Leg (Right)", "Impedance of Whole Body","Leg Fat Mass (Left)","Leg Fat Mass (Right)", "Leg Fat Percentage (Left)","Leg Fat Percentage (Right)", "Leg Fat-Free Mass (Left)", "Leg Fat-Free Mass (Right)","Leg Pain on Walking","Leg Pain on Walking : Action Taken", "Leg Pain on Walking : Effect of Standing Still", "Leg Predicted Mass (Left)","Leg Predicted Mass (Right)", "Maximum Heart Rate During Fitness Test", "Maximum Workload During Fitness Test", "Number of Days/Week of Moderate Physical Activity 10+ Minutes", "Number of Days/Week of Vigorous Physical Activity 10+ Minutes" ,"Number of Days/Week Walked 10+ Minutes", "Obesity","Obesity, Other/Unspecified", "Overall Health Rating","Target Heart Rate Achieved", "Trunk Fat Mass", "Trunk Fat Percentage", "Trunk Fat-Free Mass","Trunk Predicted Mass", "Types of Physical Activity in Last 4 Weeks: Heavy Diy (Eg: Weeding, Lawn Mowing, Carpentry, Digging)", "Types of Physical Activity in Last 4 Weeks: Light Diy (Eg: Pruning, Watering the Lawn)", "Types of Physical Activity in Last 4 Weeks: None of the above" ,"Types of Physical Activity in Last 4 Weeks: Other Exercises (Eg: Swimming, Cycling, Keep Fit, Bowling)", "Types of Physical Activity in Last 4 Weeks: Strenuous Sports", "Types of Physical Activity in Last 4 Weeks: Walking for Pleasure (not as a Means of Transport)", "Types of Transport Used (Excluding Work): Cycle", "Types of Transport Used (Excluding Work): Walk", "Used an Inhaler for Chest Within Last Hour", "Usual Walking Pace", "Waist Circumference","Weight", "Whole Body Fat Mass","Whole Body Fat-Free Mass", "Whole Body Water Mass")

fitness_traits2 <- c(
"Arm Fat Mass (Left)",
"Arm Fat Mass (Right)" ,
"Arm Fat Percentage (Left)",
"Arm Fat Percentage (Right)" ,
"Arm Fat-Free Mass (Left)" ,
"Arm Fat-Free Mass (Right)",
"Arm Predicted Mass (Left)",
"Arm Predicted Mass (Right)" ,
"Basal Metabolic Rate" ,
"Body Fat Percentage",
"Body Mass Index (Bmi)",
"Diagnoses - Main Icd: E Obesity",
"Diastolic Blood Pressure, Automated Reading",
"Diastolic Blood Pressure, Manual Reading" ,
"Duration of Fitness Test" ,
"Duration of Heavy Diy",
"Duration of Light Diy",
"Duration of Moderate Activity",
"Duration of Other Exercises",
"Duration of Strenuous Sports" ,
"Duration of Vigorous Activity",
"Duration of Walks",
"Duration of Worst Depression" ,
"Duration Walking for Pleasure",
"Falls in the Last Year" ,
"Frequency of Heavy Diy in Last  Weeks" ,
"Frequency of Light Diy in Last  Weeks" ,
"Frequency of Other Exercises in Last  Weeks" ,
"Frequency of Stair Climbing in Last  Weeks",
"Hand Grip Strength (Left)",
"Hand Grip Strength (Right)" ,
"Hip Circumference",
"Impedance of Arm (Left)",
"Impedance of Arm (Right)" ,
"Impedance of Leg (Left)",
"Impedance of Leg (Right)" ,
"Impedance of Whole Body",
"Leg Fat Mass (Left)",
"Leg Fat Mass (Right)" ,
"Leg Fat Percentage (Left)",
"Leg Fat Percentage (Right)" ,
"Leg Fat-Free Mass (Left)" ,
"Leg Fat-Free Mass (Right)",
"Leg Predicted Mass (Left)",
"Leg Predicted Mass (Right)" ,
"Maximum Heart Rate During Fitness Test" ,
"Maximum Workload During Fitness Test" ,
"Number of Days/Week of Moderate Physical Activity + Minutes",
"Number of Days/Week of Vigorous Physical Activity + Minutes",
"Number of Days/Week Walked + Minutes" ,
# "Obesity",
# "Obesity, Other/Unspecified" ,
"Overall Health Rating",
"Systolic Blood Pressure, Automated Reading" ,
"Systolic Blood Pressure, Manual Reading",
"Transport Type for Commuting to Job Workplace: Car/Motor Vehicle" ,
"Transport Type for Commuting to Job Workplace: Cycle" ,
"Transport Type for Commuting to Job Workplace: Public Transport",
"Transport Type for Commuting to Job Workplace: Walk",
"Trunk Fat Mass" ,
"Trunk Fat Percentage" ,
"Trunk Fat-Free Mass",
"Trunk Predicted Mass" ,
"Types of Physical Activity in Last  Weeks: Heavy Diy (Eg: Weeding, Lawn Mowing, Carpentry, Digging)" ,
"Types of Physical Activity in Last  Weeks: Light Diy (Eg: Pruning, Watering the Lawn)" ,
"Types of Physical Activity in Last  Weeks: None of the above",
"Types of Physical Activity in Last  Weeks: Other Exercises (Eg: Swimming, Cycling, Keep Fit, Bowling)" ,
"Types of Physical Activity in Last  Weeks: Strenuous Sports" ,
"Types of Physical Activity in Last  Weeks: Walking for Pleasure (not as a Means of Transport)" ,
"Usual Walking Pace" ,
"Waist Circumference",
"Weight" ,
"Weight Change Compared with  Year Ago" ,
"Weight Change During Worst Episode of Depression: both Gained and Lost some Weight During the Episode",
"Weight Change During Worst Episode of Depression: Gained Weight",
"Weight Change During Worst Episode of Depression: Lost Weight",
"Weight Change During Worst Episode of Depression: Stayed About the Same or Was on a Diet" ,
"Weight, Manual Entry" ,
"Wheeze or Whistling in the Chest in Last Year",
"Whole Body Fat Mass",
"Whole Body Fat-Free Mass" ,
"Whole Body Water Mass"
)

alcohol_traits <- c(
"Alcohol Drinker Status: Never",
"Alcohol Drinker Status: Previous" ,
"Alcohol Intake Frequency.",
"Alcohol Intake Versus  Years Previously",
"Alcohol Usually Taken with Meals" ,
"Average Weekly Beer Plus Cider Intake",
"Average Weekly Champagne Plus White Wine Intake",
"Average Weekly Fortified Wine Intake" ,
"Average Weekly Intake of Other Alcoholic Drinks",
"Average Weekly Red Wine Intake" ,
"Average Weekly Spirits Intake",
"Former Alcohol Drinker" ,
"Reason for Reducing Amount of Alcohol Drunk: Health Precaution" )

education_traits <- c(
"Age Completed Full Time Education" ,
"Financial Situation Satisfaction" ,
"Fluid Intelligence Score" ,
"Job Code - Deduced: Primary and Nursery Education Teaching Professionals" ,
"Job Coding: Education Officer, Director of Education, Curriculum Development Officer" ,
"Job Coding: Educational Assistant, Classroom Assistant, Special Needs Helper" ,
"Job Coding: Further Education Teaching Professional, College Lecturer/Professor",
"Job Coding: Higher Education Teaching Professional, University Lecturer/Professor (Including College/University Head/Vice Chancellor)",
"Job Coding: Other Teaching Professional Including Private Tutor, Tefl (Teaching English as a Foreign Language) Teacher; Tutor at Adult Education Centre, Etc.",
"Job Coding: Registrar or Senior Administrator of Educational Establishment, Bursar, Registrar, University Administrator",
"Job Coding: School Inspector, Education Inspector",
"Job Involves Heavy Manual or Physical Work" ,
"Job Involves Mainly Walking or Standing",
"Job Involves Shift Work",
"Job Soc Coding: Education Officers, School Inspectors",
"Job Soc Coding: Educational Assistants" ,
"Job Soc Coding: Further Education Teaching Professionals" ,
"Job Soc Coding: Higher Education Teaching Professionals",
"Job Soc Coding: Primary and Nursery Education Teaching Professionals" ,
"Job Soc Coding: Registrars and Senior Administrators of Educational Establishments" ,
"Job Soc Coding: Secondary Education Teaching Professionals" ,
"Job Soc Coding: Special Needs Education Teaching Professionals" ,
"Mean Time to Correctly Identify Matches",
"Prospective Memory Result",
"Qualifications: a Levels/as Levels or Equivalent" ,
"Qualifications: College or University Degree",
"Qualifications: Cses or Equivalent" ,
"Qualifications: None of the above",
"Qualifications: Nvq or Hnd or Hnc or Equivalent",
"Qualifications: o Levels/Gcses or Equivalent" ,
"Qualifications: Other Professional Qualifications Eg: Nursing, Teaching",
"Year Ended Full Time Education"
)

unique_traits <- c("Adopted as a Child" ,                                                                                                                                          
"Age at First Episode of Depression" ,
"Age at First Live Birth",
"Age at Last Episode of Depression",
"Age at Last Live Birth" ,
"Age Started Oral Contraceptive Pill",
"Age when Periods Started (Menarche)",
"Average Total Household Income Before Tax",
"Bilateral Oophorectomy (both Ovaries Removed)",
"Bipolar and Major Depression Status: Bipolar i Disorder",
"Bipolar and Major Depression Status: Bipolar Ii Disorder" ,
"Bipolar and Major Depression Status: No Bipolar or Depression",
"Bipolar and Major Depression Status: Probable Recurrent Major Depression (Moderate)",
"Bipolar and Major Depression Status: Probable Recurrent Major Depression (Severe)",
"Bipolar and Major Depression Status: Single Probable Major Depression Episode",
"Bipolar Disorder Status",
"Birth Weight" ,
"Birth Weight of First Child",
"Breastfed as a Baby",
# "Depression" ,
"Depression Possibly Related to Childbirth",
"Depression Possibly Related to Stressful or Traumatic Event",
"Diagnoses - Main Icd: F Schizophrenia",
"Diagnoses - Main Icd: F Depressive Episode" ,
"Diagnoses - Main Icd: F Recurrent Depressive Disorder",
"Ever Depressed for a Whole Week",
"Ever Had Period Extreme Irritability" ,
"Ever Had Prolonged Feelings of Sadness or Depression" ,
"Ever Highly Irritable/Argumentative for  Days" ,
"Ever Manic/Hyper for  Days",
"Ever Unenthusiastic/Disinterested for a Whole Week",
"Fed-Up Feelings",
"Feelings of Tiredness During Worst Episode of Depression" ,
"Feelings of Worthlessness During Worst Period of Depression",
"Fraction of Day Affected During Worst Episode of Depression",
"Frequency of Depressed Days During Worst Episode of Depression" ,
"Frequency of Depressed Mood in Last  Weeks",
"Frequency of Tenseness / Restlessness in Last  Weeks",
"Frequency of Tiredness / Lethargy in Last  Weeks",
"Frequency of Travelling from Home to Job Workplace" ,
"Frequency of Unenthusiasm / Disinterest in Last  Weeks",
"Frequency of Walking for Pleasure in Last  Weeks",
"Friendships Satisfaction" ,
"General Happiness",
"General Happiness with Own Health",
"Had Menopause",
"Irritability" ,
"Length of Menstrual Cycle",
"Lifetime Number of Depressed Periods" ,
"Loneliness, Isolation",
"Longest Period of Depression" ,
"Longest Period of Mania or Irritability",
"Manic/Hyper Symptoms: None of the above",
"Manifestations of Mania or Irritability: i Needed less Sleep than Usual",
"Manifestations of Mania or Irritability: i Was Easily Distracted" ,
"Manifestations of Mania or Irritability: i Was more Active than Usual",
"Manifestations of Mania or Irritability: i Was more Confident than Usual" ,
"Manifestations of Mania or Irritability: i Was more Creative or Had more Ideas than Usual",
"Manifestations of Mania or Irritability: i Was more Restless than Usual",
"Manifestations of Mania or Irritability: i Was more Talkative than Usual" ,
"Manifestations of Mania or Irritability: My Thoughts Were Racing" ,
"Mental Health Problems Ever Diagnosed by a Professional: Anorexia Nervosa",
"Mental Health Problems Ever Diagnosed by a Professional: Depression",
"Mental Health Problems Ever Diagnosed by a Professional: Mania, Hypomania, Bipolar or Manic-Depression" ,
"Miserableness",
"Mood Swings",
"Nervous Feelings" ,
"Neuroticism Score",
"Non-Cancer Illness Code, Self-Reported: Anorexia/Bulimia/Other Eating Disorder" ,
"Non-Cancer Illness Code, Self-Reported: Depression" ,
"Non-Cancer Illness Code, Self-Reported: Mania/Bipolar Disorder/Manic Depression",
"Professional Informed About Depression" ,
"Relative Age of First Facial Hair",
"Relative Age Voice Broke" ,
# "Schizophrenia or Delusion",
# "Schizophrenia, Schizotypal and Delusional Disorders",
"Seen a Psychiatrist for Nerves, Anxiety, Tension or Depression" ,
"Seen Doctor (Gp) for Nerves, Anxiety, Tension or Depression",
"Sensitivity / Hurt Feelings",
"Severity of Problems Due to Mania or Irritability",
"Shortness of Breath Walking on Level Ground",
"Sitting Height" ,
"Sleep Duration" ,
"Sleeplessness / Insomnia" ,
"Snoring",
"Standing Height",
"Substances Taken for Depression: Drugs or Alcohol (more than Once)",
"Substances Taken for Depression: Medication Prescribed to you (for at Least Two Weeks)" ,
"Substances Taken for Depression: Unprescribed Medication (more than Once)",
"Suffer from 'nerves'" ,
"Tense / 'Highly Strung'",
"Thoughts of Death During Worst Depression",
"Townsend Deprivation Index at Recruitment",
"Types of Transport Used (Excluding Work): Car/Motor Vehicle",
"Types of Transport Used (Excluding Work): Cycle",
"Types of Transport Used (Excluding Work): None of the above",
"Types of Transport Used (Excluding Work): Public Transport" ,
"Types of Transport Used (Excluding Work): Walk" ,
"Used an Inhaler for Chest Within Last Hour" ,
"Vascular/Heart Problems Diagnosed by Doctor: None of the above" ,
"Vitamin and Mineral Supplements: Multivitamins +/- Minerals",
"Vitamin and Mineral Supplements: None of the above" ,
"Vitamin and Mineral Supplements: Vitamin a" ,
"Vitamin and Mineral Supplements: Vitamin b" ,
"Vitamin and Mineral Supplements: Vitamin c" ,
"Vitamin and Mineral Supplements: Vitamin d" ,
"Vitamin and Mineral Supplements: Vitamin e" ,
"Why Reduced Smoking: None of the above" ,
"Why Stopped Smoking: None of the above" ,
"Work/Job Satisfaction",
"Worrier / Anxious Feelings" ,
"Worry Too Long after Embarrassment")

library(dplyr)
final_columns3 <- final_columns2 %>% filter(h2_obs > 0)
    
final_columns3$cluster <- "Unique"
final_columns3$cluster[which(final_columns3$Phenotype %in% fitness_traits2)] <- "Fitness"
final_columns3$cluster[which(final_columns3$Phenotype %in% alcohol_traits)] <- "Alcohol"
final_columns3$cluster[which(final_columns3$Phenotype %in% education_traits)] <- "Education"
final_columns3$cluster[which(final_columns3$Phenotype %in% unique_traits)] <- "Unique"


final_columns3$rg_lower <-  final_columns3$rg - final_columns3$se
final_columns3$rg_upper <-  final_columns3$rg + final_columns3$se



nomsigs <- final_columns3 %>% filter(p<.01) # nominal
vecnomsigs <- sort(unique(nomsigs$Phenotype)) # include only nominal sig values 
`%notin%` <- Negate(`%in%`)
final_columns3 <- unique(final_columns3) %>% filter(Phenotype %in% vecnomsigs) %>% filter(display_outcome %notin% c("Ever Smokers (>100 lifetime cigarettes)", "Ever Smokers (>100 lifetime cigarettes) †", "Never Smokers (<100 lifetime cigarettes)", "Never Smokers (<100 lifetime cigarettes) †"))

sort(unique(final_columns3$display_outcome))
# summary(final_columns3)


nom_sigoverall <-  final_columns3 %>% filter(display_outcome == "Lung Cancer")
nom_sigoverall <- nom_sigoverall[order(nom_sigoverall$rg),]
nom_traitordervec <- unique(nom_sigoverall$Phenotype)
# View(nom_traitordervec)
final_columns3$Phenotype <- factor(final_columns3$Phenotype, levels = nom_traitordervec)

final_columns3$combined <- paste(final_columns3$outcome, final_columns3$Phenotype)
final_columns3 <- distinct(final_columns3,combined, .keep_all= TRUE)


final_columns3 <- final_columns3 %>% mutate(display_outcome2 = case_when( 
    outcome == "overall" ~ "Lung Cancer", 
    outcome == "overall_filtered" ~ "Lung Cancer*", 
    outcome == "adeno" ~ "Adenocarcinoma (LUAD)", 
    outcome == "adeno_filtered" ~ "Adenocarcinoma (LUAD)*", 
    outcome == "small" ~ "Small Cell Carcinoma (SCLC)", 
    outcome == "small_filtered" ~ "Small Cell Carcinoma (SCLC)*", 
    outcome == "squam" ~ "Squamous Cell Carcinoma (LUSC)", 
    outcome == "squam_filtered" ~ "Squamous Cell Carcinoma (LUSC)*", 
    outcome == "ever" ~ "Ever Smokers (>100 lifetime cigarettes)", 
    outcome == "ever_filtered" ~ "Ever Smokers (>100 lifetime cigarettes)*", 
    outcome == "never" ~ "Never Smokers (<100 lifetime cigarettes)", 
    outcome == "never_filtered" ~ "Never Smokers (<100 lifetime cigarettes)*"))

final_columns3$display_outcome2 <- factor(final_columns3$display_outcome2, levels = c("Lung Cancer", "Lung Cancer*", "Adenocarcinoma (LUAD)",  "Adenocarcinoma (LUAD)*", "Small Cell Carcinoma (SCLC)", "Small Cell Carcinoma (SCLC)*", "Squamous Cell Carcinoma (LUSC)",  "Squamous Cell Carcinoma (LUSC)*"))



library(ggplot2)


cohorted <- final_columns3 %>% filter(cluster != "Unique")



theme_classic_rwp <- function (base_size = 11, base_family = "", base_line_size = base_size/22, 
    base_rect_size = base_size/22) 
{
    theme_bw(base_size = base_size, base_family = base_family, 
        base_line_size = base_line_size, base_rect_size = base_rect_size) %+replace% 
        theme(panel.border = element_blank(), panel.grid.major.y = element_line(colour = "gray", linetype = "dotted"), 
            panel.grid.minor = element_blank(), axis.line = element_line(colour = "black", 
                size = rel(1)), legend.key = element_blank(), 
            strip.background = element_rect(fill = "white", colour = "black", 
                size = rel(2)), complete = TRUE)
}






cohorted <- dplyr::filter(cohorted, !grepl("filtered",outcome))
cohorted <- dplyr::filter(cohorted, !grepl("Job Soc Coding",Phenotype))
cohorted <- dplyr::filter(cohorted, !grepl("Job Coding",Phenotype))
cohorted <- dplyr::filter(cohorted, !grepl("Weight Change",Phenotype))
cohorted <- dplyr::filter(cohorted, !grepl("Transport Type",Phenotype))


#setting up the basic plot




# for thesis figures
[1] "Alcohol"   "Education" "Fitness"  

cohorted$Phenotype <- str_replace(cohorted$Phenotype, "Alcohol Intake Frequency.", "Alcohol Intake Frequency" )
cohorted$Phenotype <- str_replace(cohorted$Phenotype, "o Levels", "O Levels" )
cohorted$Phenotype <- str_replace(cohorted$Phenotype, "a Levels/as", "A Levels/as" )

cohorted <- cohorted[order(cohorted$rg),]
nom_traitordervec <- unique(cohorted$Phenotype)
cohorted$Phenotype <- factor(cohorted$Phenotype, levels = nom_traitordervec)



library(stringr)
tmp <- dplyr::filter(cohorted, !grepl("Other Professional Qualifications E",Phenotype))
tmp <- dplyr::filter(tmp, !grepl("Nvq or Hnd or Hnc o",Phenotype))

tmp <- dplyr::filter(tmp, !grepl("Fitness",cluster))
# tmp$Phenotype <- str_replace(tmp$Phenotype, "Alcohol Intake Frequency.", "Alcohol Intake Frequency." )


sort(unique(tmp$cluster))
p <- ggplot(data=tmp, aes(y=Phenotype, x=rg, xmin=rg_lower, xmax=rg_upper, color = display_outcome2))+ 
geom_errorbarh(height=.1,position = position_dodge(width = .8)) +
geom_point(position = position_dodge(width = .8),size=3)+
theme_classic_rwp() +
geom_vline(xintercept=0, color="black", linetype="dashed", alpha=.5) +
facet_grid(cluster~., scales= "free", space="free") +
theme(text = element_text(color="black", size = 22),
          legend.position="bottom",
          legend.justification = "right",
          plot.title = element_text(hjust = 0.5),
          plot.margin = margin(.5,.5,.5,.5,"cm"), 
          axis.title.x = element_text(color="black", face="bold", vjust = -0.8, hjust = 0.5),
          axis.text.x = element_text(angle = 0, vjust = 0, color="black", size = 12),
          axis.title.y = element_text(color="black",  face="bold"),
          axis.text.y = element_text(color="black"),
          legend.title = element_text(color="black",vjust = 0, hjust = 0),
          # legend.text = element_text(color="black", hjust = -1),
          # legend.text.align = -1,
          panel.spacing.x = unit(1.25, "lines"),
          panel.border = element_rect(fill=NA,color="gray90", size=0.4, linetype="solid")) +
          labs(title = "", x = "rg +/- se"  , y = "",  color = "")
ggsave(p, file="Presentation rg alcohol education.pdf", path ="/Users/rowlandpettit/Desktop/", width = 15, height=8, dpi=900)


# fitness for thesis
tmp <- cohorted
tmp <- dplyr::filter(tmp, !grepl("Leg",Phenotype))
tmp <- dplyr::filter(tmp, !grepl("Arm",Phenotype))
tmp <- dplyr::filter(tmp, grepl("Fitness",cluster))
tmp <- dplyr::filter(tmp, !grepl("Whistling",Phenotype))
tmp <- dplyr::filter(tmp, !grepl("alls in the Last",Phenotype))
tmp <- dplyr::filter(tmp, !grepl("Diastolic",Phenotype))




sort(unique(tmp$cluster))
p <- ggplot(data=tmp, aes(y=Phenotype, x=rg, xmin=rg_lower, xmax=rg_upper, color = display_outcome2))+ 
geom_errorbarh(height=.1,position = position_dodge(width = .8)) +
geom_point(position = position_dodge(width = .8),size=3)+
theme_classic_rwp() +
geom_vline(xintercept=0, color="black", linetype="dashed", alpha=.5) +
facet_grid(cluster~., scales= "free", space="free") +
theme(text = element_text(color="black", size = 22),
          legend.position="bottom",
          legend.justification = "right",
          plot.title = element_text(hjust = 0.5),
          plot.margin = margin(.5,.5,.5,.5,"cm"), 
          axis.title.x = element_text(color="black", face="bold", vjust = -0.8, hjust = 0.5),
          axis.text.x = element_text(angle = 0, vjust = 0, color="black", size = 12),
          axis.title.y = element_text(color="black",  face="bold"),
          axis.text.y = element_text(color="black"),
          legend.title = element_text(color="black",vjust = 0, hjust = 0),
          # legend.text = element_text(color="black", hjust = -1),
          # legend.text.align = -1,
          panel.spacing.x = unit(1.25, "lines"),
          panel.border = element_rect(fill=NA,color="gray90", size=0.4, linetype="solid")) +
          labs(title = "", x = "rg +/- se"  , y = "",  color = "")
ggsave(p, file="Presentation rg fitness.pdf", path ="/Users/rowlandpettit/Desktop/", width = 15, height=8, dpi=900)


sort(unique(tmp$Phenotype))












uniquplot <- final_columns3 %>% filter(cluster == "Unique")
uniquplot$specifictraits <- "Specific"

sort(unique(uniquplot$Phenotype))

uniquplot <- dplyr::filter(uniquplot, !grepl("Job",Phenotype))
uniquplot <- dplyr::filter(uniquplot, !grepl("Father",Phenotype))
uniquplot <- dplyr::filter(uniquplot, !grepl("Weight Change",Phenotype))
uniquplot <- dplyr::filter(uniquplot, !grepl("Reason for Glass",Phenotype))
uniquplot <- dplyr::filter(uniquplot, !grepl("Medication for Pain Relief",Phenotype))
uniquplot <- dplyr::filter(uniquplot, !grepl("Substances",Phenotype))
uniquplot <- dplyr::filter(uniquplot, !grepl("Activities Undertaken",Phenotype))
uniquplot <- dplyr::filter(uniquplot, !grepl("How are People in Household ",Phenotype))
uniquplot <- dplyr::filter(uniquplot, !grepl("Pain",Phenotype))
uniquplot <- dplyr::filter(uniquplot, !grepl("None of the above",Phenotype))

None of the above

library(stringr)
# Types of Physical Activity in Last 4 Weeks: 
uniquplot$Phenotype <- str_replace(uniquplot$Phenotype, "Types of Physical Activity in Last 4 Weeks: ", "" )
uniquplot$Phenotype <- str_replace(uniquplot$Phenotype, "Medication for Cholesterol, Blood Pressure or Diabetes: ", "" )
uniquplot$Phenotype <- str_replace(uniquplot$Phenotype, "Current Employment Status: ", "" )


tmp <- uniquplot[order(uniquplot$rg),]
traitordervec <- unique(tmp$Phenotype)
uniquplot$Phenotype <- factor(uniquplot$Phenotype, levels = traitordervec)

colnames(uniquplot)

#setting up the basic plot
p <- ggplot(data=uniquplot, aes(y=Phenotype, x=rg, xmin=rg_lower, xmax=rg_upper, color = display_outcome2))+ 
geom_errorbarh(height=.1,position = position_dodge(width = .8)) +
geom_point(position = position_dodge(width = .8),size=2.5)+
theme_classic_rwp() +
coord_cartesian(xlim=c(-.5,.5))+
geom_vline(xintercept=0, color="black", linetype="dashed", alpha=.5) +
facet_grid(specifictraits~., scales= "free", space="free") +
# theme(text = element_text(color="black"),
#           plot.margin = margin(.5,.5,.5,.5,"cm"), 
#           axis.title.x = element_text(color="black", face="bold", hjust = 0.5),
#           axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0, color="black"),
#           axis.title.y = element_text(color="black",  face="bold"),
#           axis.text.y = element_text(color="black"),
#           legend.title = element_text(color="black"),
#           legend.text=element_text(color="black"),
#           panel.border = element_rect(fill=NA,color="gray90", size=0.5, linetype="solid")) +
theme(text = element_text(color="black", size = 18),
          legend.position="bottom",
          legend.justification = "right",
          plot.title = element_text(hjust = 0.5),
          plot.margin = margin(.5,.5,.5,.5,"cm"), 
          axis.title.x = element_text(color="black", face="bold", vjust = -0.8, hjust = 0.5),
          axis.text.x = element_text(angle = 0, vjust = 0, color="black", size = 12),
          axis.title.y = element_text(color="black",  face="bold"),
          axis.text.y = element_text(color="black"),
          legend.title = element_text(color="black",vjust = 0, hjust = 0),
          legend.text = element_text(color="black", hjust = -1),
          legend.text.align = -1,
          panel.spacing.x = unit(1.25, "lines"),
          panel.border = element_rect(fill=NA,color="gray90", size=0.4, linetype="solid")) +
          labs(title = "", x = "rg +/- se"  , y = "Nominally Significant (p < 0.05) Traits",  color = "* indicates\nremoval of smoking\nrelated SNPs")

p
# ggsave(p, file="Figure 8.pdf", path ="/Users/rowlandpettit/Documents/Axis/academics/research/ictr/amos/ldsr/lung/ldsr_lung_ii/manuscript/naturesr_revision/manuscript/tables and figures/", width = 15, height=15, dpi=900)
ggsave(p, file="Figure 8z.pdf", path ="/Users/rowlandpettit/Desktop/", width = 15, height=20, dpi=900)










# 
# 
# #this changes the features of the overall effects
# #one could resize, reshape, or recolor these points if desired
# geom_point(data=subset(my_plot_data, Comparison=="All"), color="Black", size=2)+ 


# #sets the scales
# #note that I reverse the y axis to correctly order the effect #sizes based on my index variable
# scale_x_continuous(limits=c(-2.5,1), breaks = c(-2.5:1), name=xname)+
# scale_y_continuous(name = "", breaks=1:19, labels = my_plot_data$Study, trans="reverse")+
# 


# #faceting based on my subgroups
# facet_grid(Comparison~., scales= "free", space="free")+
# 
# #thematic stuff
# ggtitle("Target Effects")+
# theme_minimal()+
# theme(text=element_text(family="Times",size=18, color="black"))+
# theme(panel.spacing = unit(1, "lines"))
# 
# p

```


















































